import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "#f5f6f8",
    color: "#111827",
  },
  container: {
    maxWidth: "1120px",
    margin: "0 auto",
    padding: "24px clamp(14px, 4vw, 22px) 48px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "16px",
    flexWrap: "wrap",
    marginBottom: "22px",
  },
  logo: {
    fontSize: "30px",
    fontWeight: 800,
    color: "#0f172a",
    lineHeight: 1,
  },
  title: {
    margin: "8px 0 0",
    fontSize: "22px",
    lineHeight: 1.2,
  },
  subTitle: {
    margin: "8px 0 0",
    color: "#64748b",
    fontSize: "13px",
    lineHeight: 1.55,
  },
  backButton: {
    height: "36px",
    padding: "0 14px",
    borderRadius: "10px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#111827",
    fontSize: "13px",
    fontWeight: 700,
    cursor: "pointer",
  },
  headerRight: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: "8px",
  },
  accountInfo: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: "10px",
    marginBottom: "14px",
  },
  summaryCard: {
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "14px",
  },
  summaryLabel: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
  },
  summaryValue: {
    marginTop: "8px",
    fontSize: "24px",
    fontWeight: 800,
  },
  layout: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(280px, 100%), 1fr))",
    gap: "14px",
    alignItems: "start",
  },
  panel: {
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "18px",
  },
  panelTitle: {
    margin: 0,
    fontSize: "17px",
  },
  panelTopRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
    marginBottom: "12px",
  },
  panelHint: {
    margin: "6px 0 14px",
    color: "#64748b",
    fontSize: "12px",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(170px, 100%), 1fr))",
    gap: "10px",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: "7px",
    marginBottom: "12px",
  },
  label: {
    color: "#374151",
    fontSize: "12px",
    fontWeight: 800,
  },
  input: {
    width: "100%",
    height: "42px",
    borderRadius: "10px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#111827",
    padding: "0 12px",
    fontSize: "13px",
    outline: "none",
  },
  textarea: {
    minHeight: "96px",
    padding: "12px",
    resize: "vertical",
    lineHeight: 1.5,
  },
  primaryButton: {
    width: "100%",
    height: "44px",
    borderRadius: "10px",
    border: "none",
    background: "#111827",
    color: "#ffffff",
    fontSize: "14px",
    fontWeight: 800,
    cursor: "pointer",
  },
  ghostButton: {
    height: "34px",
    padding: "0 12px",
    borderRadius: "9px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#111827",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
  },
  exportButton: {
    height: "30px",
    padding: "0 10px",
    borderRadius: "8px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#111827",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
  },
  dangerButton: {
    height: "34px",
    padding: "0 12px",
    borderRadius: "9px",
    border: "1px solid #fecaca",
    background: "#fff1f2",
    color: "#dc2626",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
  },
  tabs: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "8px",
    marginBottom: "12px",
  },
  tab: {
    height: "38px",
    borderRadius: "10px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#475569",
    fontSize: "13px",
    fontWeight: 800,
    cursor: "pointer",
  },
  activeTab: {
    height: "38px",
    borderRadius: "10px",
    border: "1px solid #111827",
    background: "#111827",
    color: "#ffffff",
    fontSize: "13px",
    fontWeight: 800,
    cursor: "pointer",
  },
  orderList: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  orderCard: {
    width: "100%",
    textAlign: "left",
    border: "1px solid #e5e7eb",
    background: "#ffffff",
    borderRadius: "12px",
    padding: "13px",
    cursor: "pointer",
  },
  selectedOrderCard: {
    width: "100%",
    textAlign: "left",
    border: "1px solid #111827",
    background: "#f8fafc",
    borderRadius: "12px",
    padding: "13px",
    cursor: "pointer",
  },
  orderTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "8px",
  },
  woNo: {
    color: "#334155",
    fontSize: "12px",
    fontWeight: 800,
  },
  orderTitle: {
    marginTop: "8px",
    fontSize: "14px",
    fontWeight: 800,
    color: "#111827",
  },
  orderMeta: {
    marginTop: "5px",
    color: "#64748b",
    fontSize: "12px",
  },
  orderBottom: {
    marginTop: "10px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "8px",
    color: "#64748b",
    fontSize: "12px",
  },
  detailPanel: {
    marginTop: "14px",
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "18px",
  },
  detailHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    alignItems: "flex-start",
  },
  detailMeta: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
  },
  detailTitle: {
    margin: "6px 0 0",
    fontSize: "18px",
  },
  detailActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "8px",
    flexWrap: "wrap",
  },
  description: {
    marginTop: "14px",
    border: "1px solid #e5e7eb",
    background: "#f9fafb",
    borderRadius: "10px",
    padding: "12px",
    color: "#374151",
    fontSize: "13px",
    lineHeight: 1.6,
  },
  logForm: {
    marginTop: "16px",
    borderTop: "1px solid #e5e7eb",
    paddingTop: "16px",
  },
  logList: {
    marginTop: "18px",
  },
  sectionTitle: {
    margin: "0 0 10px",
    fontSize: "15px",
  },
  logItem: {
    border: "1px solid #e5e7eb",
    borderRadius: "10px",
    padding: "12px",
    marginBottom: "10px",
  },
  logTop: {
    display: "flex",
    justifyContent: "space-between",
    gap: "8px",
    marginBottom: "8px",
  },
  logSeq: {
    color: "#111827",
    fontSize: "12px",
    fontWeight: 800,
  },
  logDate: {
    color: "#64748b",
    fontSize: "12px",
  },
  logAction: {
    fontSize: "14px",
    fontWeight: 800,
  },
  logMemo: {
    marginTop: "7px",
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
    color: "#64748b",
    fontSize: "12px",
  },
  empty: {
    border: "1px dashed #cbd5e1",
    borderRadius: "10px",
    padding: "18px",
    color: "#64748b",
    fontSize: "13px",
    textAlign: "center",
    background: "#f8fafc",
  },
  errorBox: {
    border: "1px solid #fecaca",
    borderRadius: "10px",
    background: "#fff1f2",
    color: "#b91c1c",
    padding: "12px",
    marginBottom: "14px",
    fontSize: "13px",
    fontWeight: 700,
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "24px",
    padding: "0 9px",
    borderRadius: "999px",
    fontSize: "11px",
    fontWeight: 800,
    whiteSpace: "nowrap",
  },
  priorityLOW: {
    background: "#eff6ff",
    color: "#1d4ed8",
    border: "1px solid #bfdbfe",
  },
  priorityMID: {
    background: "#f8fafc",
    color: "#475569",
    border: "1px solid #cbd5e1",
  },
  priorityHIGH: {
    background: "#fef2f2",
    color: "#dc2626",
    border: "1px solid #fecaca",
  },
  statusOPEN: {
    background: "#ecfeff",
    color: "#0e7490",
    border: "1px solid #a5f3fc",
  },
  statusIN_PROGRESS: {
    background: "#fffbeb",
    color: "#b45309",
    border: "1px solid #fde68a",
  },
  statusCLOSED: {
    background: "#f1f5f9",
    color: "#64748b",
    border: "1px solid #cbd5e1",
  },
};

