begin;

insert into storage.buckets (id, name, public, file_size_limit)
values ('approval-attachments', 'approval-attachments', false, 31457280)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit;

create table if not exists public.approval_attachments (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.approval_documents(id) on delete cascade,
  storage_path text not null unique,
  original_name text not null,
  mime_type text,
  size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 31457280),
  uploaded_by uuid not null default auth.uid() references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index if not exists approval_attachments_document_id_idx
  on public.approval_attachments (document_id, created_at);

alter table public.approval_attachments enable row level security;

grant select, insert, delete on public.approval_attachments to authenticated;
grant usage, select on sequence public.approval_attachments_id_seq to authenticated;

drop policy if exists "approval_attachments_select_participant" on public.approval_attachments;
create policy "approval_attachments_select_participant"
  on public.approval_attachments
  for select
  to authenticated
  using (public.can_read_approval_document(document_id));

drop policy if exists "approval_attachments_insert_requester_pending" on public.approval_attachments;
create policy "approval_attachments_insert_requester_pending"
  on public.approval_attachments
  for insert
  to authenticated
  with check (
    uploaded_by = auth.uid()
    and exists (
      select 1
      from public.approval_documents document
      where document.id = document_id
        and document.requester_id = auth.uid()
        and document.status = 'pending'
    )
  );

drop policy if exists "approval_attachments_delete_requester_pending_or_admin" on public.approval_attachments;
create policy "approval_attachments_delete_requester_pending_or_admin"
  on public.approval_attachments
  for delete
  to authenticated
  using (
    public.is_approval_admin()
    or exists (
      select 1
      from public.approval_documents document
      where document.id = document_id
        and document.requester_id = auth.uid()
        and document.status = 'pending'
    )
  );

drop policy if exists "approval_attachment_objects_insert_owner" on storage.objects;
create policy "approval_attachment_objects_insert_owner"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'approval-attachments'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "approval_attachment_objects_select_participant" on storage.objects;
create policy "approval_attachment_objects_select_participant"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'approval-attachments'
    and exists (
      select 1
      from public.approval_attachments attachment
      where attachment.storage_path = name
        and public.can_read_approval_document(attachment.document_id)
    )
  );

drop policy if exists "approval_attachment_objects_delete_owner_or_admin" on storage.objects;
create policy "approval_attachment_objects_delete_owner_or_admin"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'approval-attachments'
    and (
      public.is_approval_admin()
      or (
        (storage.foldername(name))[1] = auth.uid()::text
        and (
          not exists (
            select 1
            from public.approval_attachments attachment
            where attachment.storage_path = name
          )
          or exists (
            select 1
            from public.approval_attachments attachment
            join public.approval_documents document
              on document.id = attachment.document_id
            where attachment.storage_path = name
              and document.requester_id = auth.uid()
              and document.status = 'pending'
          )
        )
      )
    )
  );

commit;
