begin;

insert into storage.buckets (id, name, public, file_size_limit)
values ('chat-attachments', 'chat-attachments', false, 31457280)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit;

create table if not exists public.chat_attachments (
  id bigint generated by default as identity primary key,
  thread_id bigint not null references public.chat_threads(id) on delete cascade,
  message_id bigint not null references public.chat_messages(id) on delete cascade,
  storage_path text not null unique,
  original_name text not null,
  mime_type text,
  size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 31457280),
  uploaded_by uuid not null default auth.uid() references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index if not exists idx_chat_attachments_thread_message
on public.chat_attachments (thread_id, message_id, created_at);

create or replace function public.is_chat_attachment_participant(target_thread_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $chat_attachment_participant$
  select exists (
    select 1
    from public.chat_participants participant
    where participant.thread_id = target_thread_id
      and participant.user_id = auth.uid()
  );
$chat_attachment_participant$;

create or replace function public.is_chat_attachment_path_participant(target_thread_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $chat_attachment_path_participant$
  select exists (
    select 1
    from public.chat_participants participant
    where participant.thread_id::text = target_thread_id
      and participant.user_id = auth.uid()
  );
$chat_attachment_path_participant$;

create or replace function public.send_chat_message_with_attachments(
  target_thread_id bigint,
  message_body text,
  attachment_rows jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public, storage
as $send_chat_message_with_attachments$
declare
  participant public.chat_participants%rowtype;
  new_message_id bigint;
  attachment jsonb;
  path text;
  file_name text;
  file_type text;
  file_size bigint;
begin
  select p.*
  into participant
  from public.chat_participants p
  where p.thread_id = target_thread_id
    and p.user_id = auth.uid();

  if not found then
    raise exception 'Only chat participants may attach files.';
  end if;

  if attachment_rows is null
    or jsonb_typeof(attachment_rows) <> 'array'
    or jsonb_array_length(attachment_rows) < 1
    or jsonb_array_length(attachment_rows) > 5 then
    raise exception 'Attach between one and five files.';
  end if;

  insert into public.chat_messages (
    thread_id,
    sender_id,
    sender_name,
    sender_team,
    body
  )
  values (
    target_thread_id,
    auth.uid(),
    participant.user_name,
    participant.team,
    coalesce(nullif(btrim(message_body), ''), '파일을 첨부했습니다.')
  )
  returning id into new_message_id;

  for attachment in
    select value from jsonb_array_elements(attachment_rows)
  loop
    path := attachment ->> 'storage_path';
    file_name := attachment ->> 'original_name';
    file_type := attachment ->> 'mime_type';
    file_size := (attachment ->> 'size_bytes')::bigint;

    if path is null
      or path not like target_thread_id::text || '/' || auth.uid()::text || '/%'
      or file_name is null
      or btrim(file_name) = ''
      or file_size <= 0
      or file_size > 31457280 then
      raise exception 'Invalid chat attachment metadata.';
    end if;

    if not exists (
      select 1
      from storage.objects object
      where object.bucket_id = 'chat-attachments'
        and object.name = path
    ) then
      raise exception 'Uploaded chat attachment object was not found.';
    end if;

    insert into public.chat_attachments (
      thread_id,
      message_id,
      storage_path,
      original_name,
      mime_type,
      size_bytes,
      uploaded_by
    )
    values (
      target_thread_id,
      new_message_id,
      path,
      file_name,
      nullif(file_type, ''),
      file_size,
      auth.uid()
    );
  end loop;

  update public.chat_threads
  set updated_at = now()
  where id = target_thread_id;

  return new_message_id;
end;
$send_chat_message_with_attachments$;

create or replace function public.validate_chat_attachment()
returns trigger
language plpgsql
security definer
set search_path = public
as $validate_chat_attachment$
begin
  if not exists (
    select 1
    from public.chat_messages message
    where message.id = new.message_id
      and message.thread_id = new.thread_id
      and message.sender_id = auth.uid()
  ) then
    raise exception 'Attachment must belong to your message in this chat thread.';
  end if;

  if new.storage_path not like new.thread_id::text || '/' || auth.uid()::text || '/%'
    or not exists (
      select 1
      from storage.objects object
      where object.bucket_id = 'chat-attachments'
        and object.name = new.storage_path
    ) then
    raise exception 'Attachment storage object does not belong to this user and thread.';
  end if;

  new.uploaded_by := auth.uid();
  return new;
end;
$validate_chat_attachment$;

drop trigger if exists trg_validate_chat_attachment on public.chat_attachments;
create trigger trg_validate_chat_attachment
before insert on public.chat_attachments
for each row execute function public.validate_chat_attachment();

create or replace function public.get_chat_attachment_admin_summary()
returns table (attachment_count bigint, total_bytes bigint)
language plpgsql
stable
security definer
set search_path = public
as $chat_attachment_admin_summary$
begin
  if not exists (
    select 1
    from public.profiles profile
    where profile.id = auth.uid()
      and profile.role = 'admin'
  ) then
    raise exception 'Administrator access required.';
  end if;

  return query
  select count(*)::bigint, coalesce(sum(attachment.size_bytes), 0)::bigint
  from public.chat_attachments attachment;
end;
$chat_attachment_admin_summary$;

alter table public.chat_attachments enable row level security;

grant select, insert on public.chat_attachments to authenticated;
grant usage, select on sequence public.chat_attachments_id_seq to authenticated;
grant execute on function public.is_chat_attachment_participant(bigint) to authenticated;
grant execute on function public.is_chat_attachment_path_participant(text) to authenticated;
grant execute on function public.send_chat_message_with_attachments(bigint, text, jsonb) to authenticated;
grant execute on function public.get_chat_attachment_admin_summary() to authenticated;

drop policy if exists "chat_attachments_select_participant" on public.chat_attachments;
create policy "chat_attachments_select_participant"
on public.chat_attachments
for select
to authenticated
using (public.is_chat_attachment_participant(thread_id));

drop policy if exists "chat_attachments_insert_participant" on public.chat_attachments;
create policy "chat_attachments_insert_participant"
on public.chat_attachments
for insert
to authenticated
with check (
  uploaded_by = auth.uid()
  and public.is_chat_attachment_participant(thread_id)
);

drop policy if exists "chat_attachment_objects_insert_participant" on storage.objects;
create policy "chat_attachment_objects_insert_participant"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'chat-attachments'
  and (storage.foldername(name))[2] = auth.uid()::text
  and public.is_chat_attachment_path_participant((storage.foldername(name))[1])
);

drop policy if exists "chat_attachment_objects_select_participant" on storage.objects;
create policy "chat_attachment_objects_select_participant"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'chat-attachments'
  and exists (
    select 1
    from public.chat_attachments attachment
    where attachment.storage_path = name
      and public.is_chat_attachment_participant(attachment.thread_id)
  )
);

drop policy if exists "chat_attachment_objects_delete_unlinked_uploader" on storage.objects;
create policy "chat_attachment_objects_delete_unlinked_uploader"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'chat-attachments'
  and (storage.foldername(name))[2] = auth.uid()::text
  and not exists (
    select 1
    from public.chat_attachments attachment
    where attachment.storage_path = name
  )
);

do $chat_attachment_realtime$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'chat_attachments'
  ) then
    alter publication supabase_realtime add table public.chat_attachments;
  end if;
end
$chat_attachment_realtime$;

commit;
