begin;

create table if not exists public.approval_documents (
  id bigint generated by default as identity primary key,
  template_key text not null,
  template_title text not null,
  title text not null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  requester_id uuid not null references auth.users(id) on delete cascade,
  requester_name text not null,
  requester_team text,
  current_step integer not null default 1,
  form_data jsonb not null default '{}'::jsonb,
  submitted_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.approval_lines (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.approval_documents(id) on delete cascade,
  step_order integer not null,
  role_label text not null,
  approver_id uuid not null references auth.users(id) on delete cascade,
  approver_name text not null,
  approver_team text,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  acted_at timestamptz,
  memo text,
  created_at timestamptz not null default now()
);

create table if not exists public.approval_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  document_id bigint not null references public.approval_documents(id) on delete cascade,
  message text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_approval_documents_requester
on public.approval_documents (requester_id, created_at desc);

create index if not exists idx_approval_documents_status
on public.approval_documents (status, created_at desc);

create index if not exists idx_approval_lines_document
on public.approval_lines (document_id, step_order);

create index if not exists idx_approval_lines_approver
on public.approval_lines (approver_id, status, created_at desc);

create index if not exists idx_approval_notifications_user
on public.approval_notifications (user_id, read_at, created_at desc);

create or replace function public.touch_approval_documents_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists approval_documents_touch_updated_at on public.approval_documents;
create trigger approval_documents_touch_updated_at
before update on public.approval_documents
for each row
execute function public.touch_approval_documents_updated_at();

create or replace function public.is_approval_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'lead', 'executive')
  );
$$;

create or replace function public.can_read_approval_document(target_document_id bigint)
returns boolean
language sql
security definer
set search_path = public
as $$
  select
    public.is_approval_admin()
    or exists (
      select 1
      from public.approval_documents d
      where d.id = target_document_id
        and d.requester_id = auth.uid()
    )
    or exists (
      select 1
      from public.approval_lines l
      where l.document_id = target_document_id
        and l.approver_id = auth.uid()
    );
$$;

alter table public.approval_documents enable row level security;
alter table public.approval_lines enable row level security;
alter table public.approval_notifications enable row level security;

drop policy if exists "approval_documents_select_participant" on public.approval_documents;
drop policy if exists "approval_documents_insert_own" on public.approval_documents;
drop policy if exists "approval_documents_update_participant" on public.approval_documents;
drop policy if exists "approval_documents_delete_owner_or_admin" on public.approval_documents;

create policy "approval_documents_select_participant"
on public.approval_documents
for select
to authenticated
using (public.can_read_approval_document(id));

create policy "approval_documents_insert_own"
on public.approval_documents
for insert
to authenticated
with check (requester_id = auth.uid());

create policy "approval_documents_update_participant"
on public.approval_documents
for update
to authenticated
using (public.can_read_approval_document(id))
with check (public.can_read_approval_document(id));

create policy "approval_documents_delete_owner_or_admin"
on public.approval_documents
for delete
to authenticated
using (requester_id = auth.uid() or public.is_approval_admin());

drop policy if exists "approval_lines_select_participant" on public.approval_lines;
drop policy if exists "approval_lines_insert_participant" on public.approval_lines;
drop policy if exists "approval_lines_update_participant" on public.approval_lines;
drop policy if exists "approval_lines_delete_owner_or_admin" on public.approval_lines;

create policy "approval_lines_select_participant"
on public.approval_lines
for select
to authenticated
using (public.can_read_approval_document(document_id));

create policy "approval_lines_insert_participant"
on public.approval_lines
for insert
to authenticated
with check (public.can_read_approval_document(document_id));

create policy "approval_lines_update_participant"
on public.approval_lines
for update
to authenticated
using (public.can_read_approval_document(document_id))
with check (public.can_read_approval_document(document_id));

create policy "approval_lines_delete_owner_or_admin"
on public.approval_lines
for delete
to authenticated
using (
  public.is_approval_admin()
  or exists (
    select 1
    from public.approval_documents d
    where d.id = approval_lines.document_id
      and d.requester_id = auth.uid()
  )
);

drop policy if exists "approval_notifications_select_own" on public.approval_notifications;
drop policy if exists "approval_notifications_insert_authenticated" on public.approval_notifications;
drop policy if exists "approval_notifications_update_own" on public.approval_notifications;
drop policy if exists "approval_notifications_delete_own" on public.approval_notifications;

create policy "approval_notifications_select_own"
on public.approval_notifications
for select
to authenticated
using (user_id = auth.uid());

create policy "approval_notifications_insert_authenticated"
on public.approval_notifications
for insert
to authenticated
with check (true);

create policy "approval_notifications_update_own"
on public.approval_notifications
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "approval_notifications_delete_own"
on public.approval_notifications
for delete
to authenticated
using (user_id = auth.uid());

commit;
