begin;

create table if not exists public.approval_attachment_deletion_logs (
  id bigint generated by default as identity primary key,
  document_id bigint,
  document_title text not null,
  storage_path text not null,
  original_name text not null,
  size_bytes bigint not null check (size_bytes >= 0),
  deletion_reason text not null check (char_length(trim(deletion_reason)) between 2 and 300),
  operation_status text not null default 'requested'
    check (operation_status in ('requested', 'completed', 'failed')),
  failure_message text,
  deleted_by uuid default auth.uid() references auth.users(id) on delete set null,
  deleted_by_name text not null default '',
  requested_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists approval_attachment_deletion_logs_requested_at_idx
  on public.approval_attachment_deletion_logs (requested_at desc);

create or replace function public.fill_approval_attachment_deletion_log_actor()
returns trigger
language plpgsql
security definer
set search_path = public
as $deletion_log_actor$
begin
  new.deleted_by := auth.uid();
  select coalesce(profile.name, '')
    into new.deleted_by_name
  from public.profiles profile
  where profile.id = auth.uid();

  new.deleted_by_name := coalesce(new.deleted_by_name, '');
  return new;
end;
$deletion_log_actor$;

drop trigger if exists trg_fill_approval_attachment_deletion_log_actor
on public.approval_attachment_deletion_logs;

create trigger trg_fill_approval_attachment_deletion_log_actor
before insert on public.approval_attachment_deletion_logs
for each row execute function public.fill_approval_attachment_deletion_log_actor();

alter table public.approval_attachment_deletion_logs enable row level security;

grant select, insert, update on public.approval_attachment_deletion_logs to authenticated;
grant usage, select on sequence public.approval_attachment_deletion_logs_id_seq to authenticated;

drop policy if exists "approval_attachment_deletion_logs_select_admin" on public.approval_attachment_deletion_logs;
create policy "approval_attachment_deletion_logs_select_admin"
on public.approval_attachment_deletion_logs
for select
to authenticated
using (public.is_system_admin());

drop policy if exists "approval_attachment_deletion_logs_insert_admin" on public.approval_attachment_deletion_logs;
create policy "approval_attachment_deletion_logs_insert_admin"
on public.approval_attachment_deletion_logs
for insert
to authenticated
with check (public.is_system_admin() and deleted_by = auth.uid());

drop policy if exists "approval_attachment_deletion_logs_update_admin" on public.approval_attachment_deletion_logs;
create policy "approval_attachment_deletion_logs_update_admin"
on public.approval_attachment_deletion_logs
for update
to authenticated
using (public.is_system_admin())
with check (public.is_system_admin() and deleted_by = auth.uid());

commit;
