begin;

create table if not exists public.equipment_orders (
  id bigint generated by default as identity primary key,
  category text not null
    check (category in ('domestic', 'overseas', 'parts')),
  order_date date not null,
  country text,
  customer text not null,
  model text not null,
  owner_name text not null,
  note text,
  manufacturing_request_approved_on date,
  purchase_request_approved_on date,
  inbound_completed_on date,
  assembly_completed_on date,
  control_completed_on date,
  test_completed_on date,
  qa_approved_on date,
  shipment_scheduled_on date,
  manufacturing_document_id bigint,
  purchase_document_id bigint,
  qa_document_id bigint,
  created_by uuid references public.profiles(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.approval_documents
add column if not exists equipment_order_id bigint
references public.equipment_orders(id) on delete set null;

alter table public.approval_documents
add column if not exists equipment_stage_key text
check (
  equipment_stage_key is null
  or equipment_stage_key in ('manufacturingRequest', 'purchaseRequest', 'qa')
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'equipment_orders_manufacturing_document_fk'
  ) then
    alter table public.equipment_orders
    add constraint equipment_orders_manufacturing_document_fk
    foreign key (manufacturing_document_id)
    references public.approval_documents(id)
    on delete set null;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'equipment_orders_purchase_document_fk'
  ) then
    alter table public.equipment_orders
    add constraint equipment_orders_purchase_document_fk
    foreign key (purchase_document_id)
    references public.approval_documents(id)
    on delete set null;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'equipment_orders_qa_document_fk'
  ) then
    alter table public.equipment_orders
    add constraint equipment_orders_qa_document_fk
    foreign key (qa_document_id)
    references public.approval_documents(id)
    on delete set null;
  end if;
end $$;

create index if not exists idx_equipment_orders_category_date
on public.equipment_orders (category, order_date desc);

create index if not exists idx_approval_documents_equipment_order
on public.approval_documents (equipment_order_id);

create or replace function public.touch_equipment_orders_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists equipment_orders_touch_updated_at on public.equipment_orders;
create trigger equipment_orders_touch_updated_at
before update on public.equipment_orders
for each row
execute function public.touch_equipment_orders_updated_at();

create or replace function public.is_equipment_order_manager()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and (
        p.role in ('admin', 'lead', 'executive')
        or p.name in (
          '신영호',
          '신상민',
          '서중석',
          '한차현',
          '이승준',
          '장동철',
          '권현진',
          '김혜정',
          '정대용',
          '이양로'
        )
      )
  );
$$;

alter table public.equipment_orders enable row level security;

drop policy if exists "equipment_orders_select_authenticated_all" on public.equipment_orders;
drop policy if exists "equipment_orders_insert_manager" on public.equipment_orders;
drop policy if exists "equipment_orders_update_manager" on public.equipment_orders;
drop policy if exists "equipment_orders_delete_manager" on public.equipment_orders;
drop policy if exists "equipment_orders_insert_authenticated_all" on public.equipment_orders;
drop policy if exists "equipment_orders_update_authenticated_all" on public.equipment_orders;

grant select, insert, update, delete on public.equipment_orders to authenticated;

create policy "equipment_orders_select_authenticated_all"
on public.equipment_orders
for select
to authenticated
using (true);

create policy "equipment_orders_insert_authenticated_all"
on public.equipment_orders
for insert
to authenticated
with check (auth.uid() is not null);

create policy "equipment_orders_update_authenticated_all"
on public.equipment_orders
for update
to authenticated
using (true)
with check (true);

create policy "equipment_orders_delete_manager"
on public.equipment_orders
for delete
to authenticated
using (public.is_equipment_order_manager());

commit;
