begin;

create table if not exists public.idea_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  author_id uuid not null references public.profiles(id) on delete cascade default auth.uid(),
  author_name text not null,
  author_team text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.idea_attachments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.idea_posts(id) on delete cascade,
  storage_path text not null unique,
  original_name text not null,
  mime_type text,
  size_bytes bigint not null check (size_bytes > 0),
  uploaded_by uuid not null references public.profiles(id) on delete cascade default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists idx_idea_posts_created_at
on public.idea_posts (created_at desc);

create index if not exists idx_idea_posts_author_id
on public.idea_posts (author_id);

create index if not exists idx_idea_attachments_post_id
on public.idea_attachments (post_id);

insert into storage.buckets (id, name, public, file_size_limit)
values ('idea-attachments', 'idea-attachments', false, 31457280)
on conflict (id) do update
set public = false,
    file_size_limit = 31457280;

alter table public.idea_posts enable row level security;
alter table public.idea_attachments enable row level security;

grant select, insert, update, delete on public.idea_posts to authenticated;
grant select, insert, update, delete on public.idea_attachments to authenticated;
grant usage, select on sequence public.idea_posts_id_seq to authenticated;
grant usage, select on sequence public.idea_attachments_id_seq to authenticated;

drop policy if exists "idea_posts_select_authenticated" on public.idea_posts;
create policy "idea_posts_select_authenticated"
on public.idea_posts
for select
to authenticated
using (true);

drop policy if exists "idea_posts_insert_own" on public.idea_posts;
create policy "idea_posts_insert_own"
on public.idea_posts
for insert
to authenticated
with check (author_id = auth.uid());

drop policy if exists "idea_posts_update_own" on public.idea_posts;
create policy "idea_posts_update_own"
on public.idea_posts
for update
to authenticated
using (author_id = auth.uid())
with check (author_id = auth.uid());

drop policy if exists "idea_posts_delete_own" on public.idea_posts;
create policy "idea_posts_delete_own"
on public.idea_posts
for delete
to authenticated
using (author_id = auth.uid());

drop policy if exists "idea_attachments_select_authenticated" on public.idea_attachments;
create policy "idea_attachments_select_authenticated"
on public.idea_attachments
for select
to authenticated
using (true);

drop policy if exists "idea_attachments_insert_post_owner" on public.idea_attachments;
create policy "idea_attachments_insert_post_owner"
on public.idea_attachments
for insert
to authenticated
with check (
  uploaded_by = auth.uid()
  and exists (
    select 1
    from public.idea_posts post
    where post.id = post_id
      and post.author_id = auth.uid()
  )
);

drop policy if exists "idea_attachments_delete_post_owner" on public.idea_attachments;
create policy "idea_attachments_delete_post_owner"
on public.idea_attachments
for delete
to authenticated
using (
  exists (
    select 1
    from public.idea_posts post
    where post.id = post_id
      and post.author_id = auth.uid()
  )
);

drop policy if exists "idea_attachment_objects_insert_own" on storage.objects;
create policy "idea_attachment_objects_insert_own"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'idea-attachments'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "idea_attachment_objects_select_authenticated" on storage.objects;
create policy "idea_attachment_objects_select_authenticated"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'idea-attachments'
  and exists (
    select 1
    from public.idea_attachments attachment
    where attachment.storage_path = name
  )
);

drop policy if exists "idea_attachment_objects_delete_owner" on storage.objects;
create policy "idea_attachment_objects_delete_owner"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'idea-attachments'
  and exists (
    select 1
    from public.idea_attachments attachment
    join public.idea_posts post on post.id = attachment.post_id
    where attachment.storage_path = name
      and post.author_id = auth.uid()
  )
);

create or replace function public.get_idea_attachment_admin_summary()
returns table (
  attachment_count bigint,
  total_bytes bigint
)
language sql
security definer
set search_path = public
as $$
  select
    count(*)::bigint as attachment_count,
    coalesce(sum(size_bytes), 0)::bigint as total_bytes
  from public.idea_attachments
  where exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
  );
$$;

grant execute on function public.get_idea_attachment_admin_summary() to authenticated;

do $idea_realtime$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'idea_posts'
  ) then
    alter publication supabase_realtime add table public.idea_posts;
  end if;
end
$idea_realtime$;

commit;
