-- ZETA shared modules schema
-- Run in Supabase SQL Editor after reviewing.
--
-- Scope:
-- - notices: main-page notices, managed by admin/lead users
-- - customers / customer_contacts: shared customer contact DB
-- - as_work_orders / as_service_logs: future A/S persistence
-- - sales_opportunities / sales_activities: future sales persistence

begin;

create extension if not exists pgcrypto;

create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  target_team text,
  pinned boolean not null default false,
  starts_on date,
  ends_on date,
  created_by uuid references public.profiles(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null default '',
  address text not null default '',
  memo text not null default '',
  created_by uuid references public.profiles(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint customers_name_unique unique (name)
);

create table if not exists public.customer_contacts (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  name text not null,
  department text not null default '',
  position text not null default '',
  phone text not null default '',
  email text not null default '',
  memo text not null default '',
  created_by uuid references public.profiles(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.as_work_orders (
  id bigint generated by default as identity primary key,
  wo_no text not null,
  customer_id bigint references public.customers(id) on delete set null,
  customer text not null default '',
  model text not null default '',
  title text not null,
  description text not null default '',
  priority text not null default 'MID' check (priority in ('LOW', 'MID', 'HIGH')),
  status text not null default 'OPEN' check (status in ('OPEN', 'IN_PROGRESS', 'CLOSED')),
  created_by uuid references public.profiles(id) on delete set null default auth.uid(),
  created_at date not null default current_date,
  updated_at date not null default current_date,
  constraint as_work_orders_wo_no_unique unique (wo_no)
);

create table if not exists public.as_service_logs (
  id bigint generated by default as identity primary key,
  work_order_id bigint not null references public.as_work_orders(id) on delete cascade,
  seq integer not null,
  action text not null,
  part text not null default '',
  memo text not null default '',
  created_by uuid references public.profiles(id) on delete set null default auth.uid(),
  created_at date not null default current_date
);

create table if not exists public.sales_opportunities (
  id bigint generated by default as identity primary key,
  division text not null check (division in ('domestic', 'overseas')),
  customer_id bigint references public.customers(id) on delete set null,
  company text not null,
  contact text not null default '',
  item text not null,
  amount numeric not null default 0,
  stage text not null default 'LEAD'
    check (stage in ('LEAD', 'MEETING', 'QUOTE', 'NEGOTIATION', 'WON', 'LOST')),
  next_action text not null default '',
  due_date date,
  created_by uuid references public.profiles(id) on delete set null default auth.uid(),
  created_at date not null default current_date,
  updated_at date not null default current_date
);

create table if not exists public.sales_activities (
  id bigint generated by default as identity primary key,
  opportunity_id bigint not null references public.sales_opportunities(id) on delete cascade,
  type text not null default '후속',
  title text not null,
  memo text not null default '',
  date date not null default current_date,
  created_by uuid references public.profiles(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

create or replace function public.is_notice_manager()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'lead', 'executive')
  );
$$;

alter table public.notices enable row level security;
alter table public.customers enable row level security;
alter table public.customer_contacts enable row level security;
alter table public.as_work_orders enable row level security;
alter table public.as_service_logs enable row level security;
alter table public.sales_opportunities enable row level security;
alter table public.sales_activities enable row level security;

do $$
declare
  policy_record record;
begin
  for policy_record in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in (
        'notices',
        'customers',
        'customer_contacts',
        'as_work_orders',
        'as_service_logs',
        'sales_opportunities',
        'sales_activities'
      )
  loop
    execute format(
      'drop policy if exists %I on %I.%I',
      policy_record.policyname,
      policy_record.schemaname,
      policy_record.tablename
    );
  end loop;
end $$;

grant select, insert, update, delete on public.notices to authenticated;
grant select, insert, update, delete on public.customers to authenticated;
grant select, insert, update, delete on public.customer_contacts to authenticated;
grant select, insert, update, delete on public.as_work_orders to authenticated;
grant select, insert, update, delete on public.as_service_logs to authenticated;
grant select, insert, update, delete on public.sales_opportunities to authenticated;
grant select, insert, update, delete on public.sales_activities to authenticated;

grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.is_notice_manager() to authenticated;

create policy "notices_select_authenticated_all"
on public.notices
for select
to authenticated
using (true);

create policy "notices_insert_managers"
on public.notices
for insert
to authenticated
with check (public.is_notice_manager());

create policy "notices_update_managers"
on public.notices
for update
to authenticated
using (public.is_notice_manager())
with check (public.is_notice_manager());

create policy "notices_delete_managers"
on public.notices
for delete
to authenticated
using (public.is_notice_manager());

create policy "customers_select_authenticated_all"
on public.customers
for select
to authenticated
using (true);

create policy "customers_insert_authenticated_all"
on public.customers
for insert
to authenticated
with check (true);

create policy "customers_update_authenticated_all"
on public.customers
for update
to authenticated
using (true)
with check (true);

create policy "customers_delete_authenticated_all"
on public.customers
for delete
to authenticated
using (true);

create policy "customer_contacts_select_authenticated_all"
on public.customer_contacts
for select
to authenticated
using (true);

create policy "customer_contacts_insert_authenticated_all"
on public.customer_contacts
for insert
to authenticated
with check (true);

create policy "customer_contacts_update_authenticated_all"
on public.customer_contacts
for update
to authenticated
using (true)
with check (true);

create policy "customer_contacts_delete_authenticated_all"
on public.customer_contacts
for delete
to authenticated
using (true);

create policy "as_work_orders_select_authenticated_all"
on public.as_work_orders
for select
to authenticated
using (true);

create policy "as_work_orders_insert_authenticated_all"
on public.as_work_orders
for insert
to authenticated
with check (true);

create policy "as_work_orders_update_authenticated_all"
on public.as_work_orders
for update
to authenticated
using (true)
with check (true);

create policy "as_work_orders_delete_authenticated_all"
on public.as_work_orders
for delete
to authenticated
using (true);

create policy "as_service_logs_select_authenticated_all"
on public.as_service_logs
for select
to authenticated
using (true);

create policy "as_service_logs_insert_authenticated_all"
on public.as_service_logs
for insert
to authenticated
with check (true);

create policy "as_service_logs_update_authenticated_all"
on public.as_service_logs
for update
to authenticated
using (true)
with check (true);

create policy "as_service_logs_delete_authenticated_all"
on public.as_service_logs
for delete
to authenticated
using (true);

create policy "sales_opportunities_select_authenticated_all"
on public.sales_opportunities
for select
to authenticated
using (true);

create policy "sales_opportunities_insert_authenticated_all"
on public.sales_opportunities
for insert
to authenticated
with check (true);

create policy "sales_opportunities_update_authenticated_all"
on public.sales_opportunities
for update
to authenticated
using (true)
with check (true);

create policy "sales_opportunities_delete_authenticated_all"
on public.sales_opportunities
for delete
to authenticated
using (true);

create policy "sales_activities_select_authenticated_all"
on public.sales_activities
for select
to authenticated
using (true);

create policy "sales_activities_insert_authenticated_all"
on public.sales_activities
for insert
to authenticated
with check (true);

create policy "sales_activities_update_authenticated_all"
on public.sales_activities
for update
to authenticated
using (true)
with check (true);

create policy "sales_activities_delete_authenticated_all"
on public.sales_activities
for delete
to authenticated
using (true);

create index if not exists idx_notices_pinned_dates
on public.notices (pinned desc, starts_on, ends_on, created_at desc);

create index if not exists idx_customer_contacts_customer_id
on public.customer_contacts (customer_id);

create index if not exists idx_as_service_logs_work_order_id
on public.as_service_logs (work_order_id);

create index if not exists idx_sales_opportunities_division
on public.sales_opportunities (division);

create index if not exists idx_sales_activities_opportunity_id
on public.sales_activities (opportunity_id);

commit;
