begin;

alter table public.equipment_orders
add column if not exists serial_no text;

alter table public.equipment_orders
add column if not exists delivery_place text;

alter table public.equipment_orders
add column if not exists note text;

alter table public.approval_documents
add column if not exists equipment_order_id bigint
references public.equipment_orders(id) on delete set null;

alter table public.approval_documents
add column if not exists equipment_stage_key text;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'approval_documents_equipment_stage_key_check'
  ) then
    alter table public.approval_documents
    add constraint approval_documents_equipment_stage_key_check
    check (
      equipment_stage_key is null
      or equipment_stage_key in ('manufacturingRequest', 'purchaseRequest', 'qa')
    );
  end if;
end $$;

create table if not exists public.approval_references (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.approval_documents(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reference_name text not null,
  reference_team text,
  created_at timestamptz not null default now(),
  unique (document_id, user_id)
);

create index if not exists idx_approval_references_document
on public.approval_references (document_id);

create index if not exists idx_approval_references_user
on public.approval_references (user_id, created_at desc);

create or replace function public.can_read_approval_document(target_document_id bigint)
returns boolean
language sql
security definer
set search_path = public
as $$
  select
    public.is_approval_admin()
    or exists (
      select 1
      from public.approval_documents d
      where d.id = target_document_id
        and d.requester_id = auth.uid()
    )
    or exists (
      select 1
      from public.approval_lines l
      where l.document_id = target_document_id
        and l.approver_id = auth.uid()
    )
    or exists (
      select 1
      from public.approval_references r
      where r.document_id = target_document_id
        and r.user_id = auth.uid()
    );
$$;

alter table public.approval_references enable row level security;

grant select, insert, delete on public.approval_references to authenticated;

drop policy if exists "approval_references_select_participant" on public.approval_references;
drop policy if exists "approval_references_insert_document_participant" on public.approval_references;
drop policy if exists "approval_references_delete_owner_or_admin" on public.approval_references;

create policy "approval_references_select_participant"
on public.approval_references
for select
to authenticated
using (user_id = auth.uid() or public.can_read_approval_document(document_id));

create policy "approval_references_insert_document_participant"
on public.approval_references
for insert
to authenticated
with check (public.can_read_approval_document(document_id));

create policy "approval_references_delete_owner_or_admin"
on public.approval_references
for delete
to authenticated
using (
  public.is_approval_admin()
  or exists (
    select 1
    from public.approval_documents d
    where d.id = approval_references.document_id
      and d.requester_id = auth.uid()
  )
);

commit;
