begin;

create table if not exists public.idea_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  author_id uuid not null references public.profiles(id) on delete cascade default auth.uid(),
  author_name text not null,
  author_team text,
  view_count integer not null default 0 check (view_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.idea_posts
add column if not exists view_count integer not null default 0 check (view_count >= 0);

create table if not exists public.idea_attachments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.idea_posts(id) on delete cascade,
  storage_path text not null unique,
  original_name text not null,
  mime_type text,
  size_bytes bigint not null check (size_bytes > 0),
  uploaded_by uuid not null references public.profiles(id) on delete cascade default auth.uid(),
  created_at timestamptz not null default now()
);

create table if not exists public.idea_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.idea_posts(id) on delete cascade,
  parent_id bigint references public.idea_comments(id) on delete cascade,
  body text not null,
  author_id uuid not null references public.profiles(id) on delete cascade default auth.uid(),
  author_name text not null,
  author_team text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.idea_reactions (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.idea_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade default auth.uid(),
  user_name text not null,
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

create table if not exists public.idea_post_views (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.idea_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade default auth.uid(),
  viewed_at timestamptz not null default now(),
  unique (post_id, user_id)
);

create table if not exists public.idea_comment_reactions (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.idea_comments(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade default auth.uid(),
  user_name text not null,
  created_at timestamptz not null default now(),
  unique (comment_id, user_id)
);

create index if not exists idx_idea_posts_created_at
on public.idea_posts (created_at desc);

create index if not exists idx_idea_posts_author_id
on public.idea_posts (author_id);

create index if not exists idx_idea_attachments_post_id
on public.idea_attachments (post_id);

create index if not exists idx_idea_comments_post_id
on public.idea_comments (post_id, created_at);

create index if not exists idx_idea_comments_parent_id
on public.idea_comments (parent_id);

create index if not exists idx_idea_reactions_post_id
on public.idea_reactions (post_id);

create index if not exists idx_idea_post_views_post_id
on public.idea_post_views (post_id);

create index if not exists idx_idea_comment_reactions_comment_id
on public.idea_comment_reactions (comment_id);

insert into storage.buckets (id, name, public, file_size_limit)
values ('idea-attachments', 'idea-attachments', false, 31457280)
on conflict (id) do update
set public = false,
    file_size_limit = 31457280;

alter table public.idea_posts enable row level security;
alter table public.idea_attachments enable row level security;
alter table public.idea_comments enable row level security;
alter table public.idea_reactions enable row level security;
alter table public.idea_post_views enable row level security;
alter table public.idea_comment_reactions enable row level security;

grant select, insert, update, delete on public.idea_posts to authenticated;
grant select, insert, update, delete on public.idea_attachments to authenticated;
grant select, insert, update, delete on public.idea_comments to authenticated;
grant select, insert, delete on public.idea_reactions to authenticated;
grant select, insert on public.idea_post_views to authenticated;
grant select, insert, delete on public.idea_comment_reactions to authenticated;
grant usage, select on sequence public.idea_posts_id_seq to authenticated;
grant usage, select on sequence public.idea_attachments_id_seq to authenticated;
grant usage, select on sequence public.idea_comments_id_seq to authenticated;
grant usage, select on sequence public.idea_reactions_id_seq to authenticated;
grant usage, select on sequence public.idea_post_views_id_seq to authenticated;
grant usage, select on sequence public.idea_comment_reactions_id_seq to authenticated;

drop function if exists public.increment_idea_post_view(bigint);

create or replace function public.increment_idea_post_view(target_post_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted boolean := false;
begin
  insert into public.idea_post_views (post_id, user_id)
  values (target_post_id, auth.uid())
  on conflict (post_id, user_id) do nothing;

  inserted := found;

  if inserted then
    update public.idea_posts
    set view_count = view_count + 1
    where id = target_post_id;
  end if;

  return inserted;
end;
$$;

create or replace function public.backfill_idea_post_view_counts()
returns void
language sql
security definer
set search_path = public
as $$
  update public.idea_posts
  set view_count = coalesce(view_counts.count_value, 0)::integer
  from (
    select post.id, count(view_record.id) as count_value
    from public.idea_posts post
    left join public.idea_post_views view_record on view_record.post_id = post.id
    group by post.id
  ) view_counts
  where public.idea_posts.id = view_counts.id
    and exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role = 'admin'
    );
$$;

grant execute on function public.increment_idea_post_view(bigint) to authenticated;
grant execute on function public.backfill_idea_post_view_counts() to authenticated;

drop policy if exists "idea_posts_select_authenticated" on public.idea_posts;
create policy "idea_posts_select_authenticated"
on public.idea_posts
for select
to authenticated
using (true);

drop policy if exists "idea_posts_insert_own" on public.idea_posts;
create policy "idea_posts_insert_own"
on public.idea_posts
for insert
to authenticated
with check (author_id = auth.uid());

drop policy if exists "idea_posts_update_own" on public.idea_posts;
create policy "idea_posts_update_own"
on public.idea_posts
for update
to authenticated
using (author_id = auth.uid())
with check (author_id = auth.uid());

drop policy if exists "idea_posts_delete_own" on public.idea_posts;
create policy "idea_posts_delete_own"
on public.idea_posts
for delete
to authenticated
using (author_id = auth.uid());

drop policy if exists "idea_attachments_select_authenticated" on public.idea_attachments;
create policy "idea_attachments_select_authenticated"
on public.idea_attachments
for select
to authenticated
using (true);

drop policy if exists "idea_attachments_insert_post_owner" on public.idea_attachments;
create policy "idea_attachments_insert_post_owner"
on public.idea_attachments
for insert
to authenticated
with check (
  uploaded_by = auth.uid()
  and exists (
    select 1
    from public.idea_posts post
    where post.id = post_id
      and post.author_id = auth.uid()
  )
);

drop policy if exists "idea_attachments_delete_post_owner" on public.idea_attachments;
create policy "idea_attachments_delete_post_owner"
on public.idea_attachments
for delete
to authenticated
using (
  exists (
    select 1
    from public.idea_posts post
    where post.id = post_id
      and post.author_id = auth.uid()
  )
);

drop policy if exists "idea_comments_select_authenticated" on public.idea_comments;
create policy "idea_comments_select_authenticated"
on public.idea_comments
for select
to authenticated
using (true);

drop policy if exists "idea_comments_insert_own" on public.idea_comments;
create policy "idea_comments_insert_own"
on public.idea_comments
for insert
to authenticated
with check (author_id = auth.uid());

drop policy if exists "idea_comments_update_own" on public.idea_comments;
create policy "idea_comments_update_own"
on public.idea_comments
for update
to authenticated
using (author_id = auth.uid())
with check (author_id = auth.uid());

drop policy if exists "idea_comments_delete_own" on public.idea_comments;
create policy "idea_comments_delete_own"
on public.idea_comments
for delete
to authenticated
using (author_id = auth.uid());

drop policy if exists "idea_reactions_select_authenticated" on public.idea_reactions;
create policy "idea_reactions_select_authenticated"
on public.idea_reactions
for select
to authenticated
using (true);

drop policy if exists "idea_reactions_insert_own" on public.idea_reactions;
create policy "idea_reactions_insert_own"
on public.idea_reactions
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "idea_reactions_delete_own" on public.idea_reactions;
create policy "idea_reactions_delete_own"
on public.idea_reactions
for delete
to authenticated
using (user_id = auth.uid());

drop policy if exists "idea_post_views_select_authenticated" on public.idea_post_views;
create policy "idea_post_views_select_authenticated"
on public.idea_post_views
for select
to authenticated
using (true);

drop policy if exists "idea_post_views_insert_own" on public.idea_post_views;
create policy "idea_post_views_insert_own"
on public.idea_post_views
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "idea_comment_reactions_select_authenticated" on public.idea_comment_reactions;
create policy "idea_comment_reactions_select_authenticated"
on public.idea_comment_reactions
for select
to authenticated
using (true);

drop policy if exists "idea_comment_reactions_insert_own" on public.idea_comment_reactions;
create policy "idea_comment_reactions_insert_own"
on public.idea_comment_reactions
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "idea_comment_reactions_delete_own" on public.idea_comment_reactions;
create policy "idea_comment_reactions_delete_own"
on public.idea_comment_reactions
for delete
to authenticated
using (user_id = auth.uid());

drop policy if exists "idea_attachment_objects_insert_own" on storage.objects;
create policy "idea_attachment_objects_insert_own"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'idea-attachments'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "idea_attachment_objects_select_authenticated" on storage.objects;
create policy "idea_attachment_objects_select_authenticated"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'idea-attachments'
  and exists (
    select 1
    from public.idea_attachments attachment
    where attachment.storage_path = name
  )
);

drop policy if exists "idea_attachment_objects_delete_owner" on storage.objects;
create policy "idea_attachment_objects_delete_owner"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'idea-attachments'
  and exists (
    select 1
    from public.idea_attachments attachment
    join public.idea_posts post on post.id = attachment.post_id
    where attachment.storage_path = name
      and post.author_id = auth.uid()
  )
);

create or replace function public.get_idea_attachment_admin_summary()
returns table (
  attachment_count bigint,
  total_bytes bigint
)
language sql
security definer
set search_path = public
as $$
  select
    count(*)::bigint as attachment_count,
    coalesce(sum(size_bytes), 0)::bigint as total_bytes
  from public.idea_attachments
  where exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
  );
$$;

grant execute on function public.get_idea_attachment_admin_summary() to authenticated;

create or replace function public.get_idea_board_admin_summary()
returns table (
  post_count bigint,
  comment_count bigint,
  reaction_count bigint,
  recent_post_count bigint
)
language sql
security definer
set search_path = public
as $$
  select
    (select count(*) from public.idea_posts)::bigint as post_count,
    (select count(*) from public.idea_comments)::bigint as comment_count,
    (
      (select count(*) from public.idea_reactions)
      + (select count(*) from public.idea_comment_reactions)
    )::bigint as reaction_count,
    (select count(*) from public.idea_posts where created_at >= now() - interval '30 days')::bigint as recent_post_count
  where exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
  );
$$;

grant execute on function public.get_idea_board_admin_summary() to authenticated;

do $idea_realtime$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'idea_posts'
  ) then
    alter publication supabase_realtime add table public.idea_posts;
  end if;
end
$idea_realtime$;

do $idea_comment_realtime$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'idea_comments'
  ) then
    alter publication supabase_realtime add table public.idea_comments;
  end if;
end
$idea_comment_realtime$;

commit;
