import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "#f5f6f8",
    color: "#111827",
  },
  container: {
    maxWidth: "1120px",
    margin: "0 auto",
    padding: "30px 22px 56px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "16px",
    flexWrap: "wrap",
    marginBottom: "18px",
  },
  logo: {
    fontSize: "30px",
    fontWeight: 800,
    color: "#0f172a",
    lineHeight: 1,
  },
  title: {
    margin: "8px 0 0",
    fontSize: "22px",
    lineHeight: 1.2,
  },
  subTitle: {
    margin: "8px 0 0",
    color: "#64748b",
    fontSize: "13px",
    lineHeight: 1.55,
  },
  backButton: {
    height: "36px",
    padding: "0 14px",
    borderRadius: "10px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#111827",
    fontSize: "13px",
    fontWeight: 700,
    cursor: "pointer",
  },
  headerRight: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: "8px",
  },
  accountInfo: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  segment: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "8px",
    marginBottom: "14px",
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "8px",
  },
  segmentButton: {
    height: "40px",
    borderRadius: "10px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#475569",
    fontSize: "14px",
    fontWeight: 800,
    cursor: "pointer",
  },
  activeSegmentButton: {
    height: "40px",
    borderRadius: "10px",
    border: "1px solid #111827",
    background: "#111827",
    color: "#ffffff",
    fontSize: "14px",
    fontWeight: 800,
    cursor: "pointer",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: "10px",
    marginBottom: "14px",
  },
  summaryCard: {
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "14px",
  },
  summaryLabel: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
  },
  summaryValue: {
    marginTop: "8px",
    fontSize: "22px",
    fontWeight: 800,
  },
  layout: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: "14px",
    alignItems: "start",
  },
  panel: {
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "18px",
  },
  panelTitle: {
    margin: 0,
    fontSize: "17px",
  },
  panelHint: {
    margin: "6px 0 14px",
    color: "#64748b",
    fontSize: "12px",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "10px",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: "7px",
    marginBottom: "12px",
  },
  label: {
    color: "#374151",
    fontSize: "12px",
    fontWeight: 800,
  },
  input: {
    width: "100%",
    height: "42px",
    borderRadius: "10px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#111827",
    padding: "0 12px",
    fontSize: "13px",
    outline: "none",
  },
  textarea: {
    minHeight: "90px",
    padding: "12px",
    resize: "vertical",
    lineHeight: 1.5,
  },
  primaryButton: {
    width: "100%",
    height: "44px",
    borderRadius: "10px",
    border: "none",
    background: "#111827",
    color: "#ffffff",
    fontSize: "14px",
    fontWeight: 800,
    cursor: "pointer",
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  card: {
    width: "100%",
    textAlign: "left",
    border: "1px solid #e5e7eb",
    background: "#ffffff",
    borderRadius: "12px",
    padding: "13px",
    cursor: "pointer",
  },
  selectedCard: {
    width: "100%",
    textAlign: "left",
    border: "1px solid #111827",
    background: "#f8fafc",
    borderRadius: "12px",
    padding: "13px",
    cursor: "pointer",
  },
  simpleCardRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    alignItems: "center",
    minHeight: "24px",
  },
  company: {
    fontSize: "14px",
    fontWeight: 800,
  },
  contact: {
    color: "#64748b",
    fontSize: "13px",
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  cardTop: {
    display: "flex",
    justifyContent: "space-between",
    gap: "10px",
    alignItems: "center",
  },
  item: {
    marginTop: "7px",
    fontSize: "13px",
    color: "#334155",
  },
  meta: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    marginTop: "9px",
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
  },
  nextAction: {
    marginTop: "10px",
    borderRadius: "10px",
    background: "#f8fafc",
    border: "1px solid #e5e7eb",
    padding: "10px",
    color: "#334155",
    fontSize: "12px",
  },
  detailPanel: {
    marginTop: "14px",
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "18px",
  },
  detailHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  detailMeta: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
  },
  detailTitle: {
    margin: "6px 0 0",
    fontSize: "18px",
  },
  deleteButton: {
    height: "34px",
    padding: "0 12px",
    borderRadius: "9px",
    border: "1px solid #fecaca",
    background: "#fef2f2",
    color: "#dc2626",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
  },
  detailGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "10px",
    marginTop: "14px",
  },
  detailBox: {
    border: "1px solid #e5e7eb",
    borderRadius: "10px",
    padding: "12px",
    background: "#f8fafc",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    fontSize: "13px",
  },
  detailLabel: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
  },
  stageBox: {
    marginTop: "16px",
    borderTop: "1px solid #e5e7eb",
    paddingTop: "16px",
  },
  stageButtons: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
    marginTop: "8px",
  },
  stageButton: {
    height: "34px",
    padding: "0 12px",
    borderRadius: "999px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#475569",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
  },
  activeStageButton: {
    height: "34px",
    padding: "0 12px",
    borderRadius: "999px",
    border: "1px solid #111827",
    background: "#111827",
    color: "#ffffff",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
  },
  activityForm: {
    marginTop: "16px",
    borderTop: "1px solid #e5e7eb",
    paddingTop: "16px",
  },
  sectionTitle: {
    margin: "0 0 12px",
    fontSize: "15px",
  },
  activityList: {
    marginTop: "18px",
  },
  activityItem: {
    border: "1px solid #e5e7eb",
    borderRadius: "10px",
    padding: "12px",
    marginBottom: "10px",
  },
  activityTop: {
    display: "flex",
    justifyContent: "space-between",
    gap: "8px",
  },
  activityType: {
    fontSize: "12px",
    fontWeight: 800,
  },
  activityDate: {
    color: "#64748b",
    fontSize: "12px",
  },
  activityTitle: {
    marginTop: "7px",
    fontSize: "14px",
    fontWeight: 800,
  },
  activityMemo: {
    marginTop: "7px",
    color: "#64748b",
    fontSize: "12px",
    lineHeight: 1.5,
  },
  empty: {
    border: "1px dashed #cbd5e1",
    borderRadius: "10px",
    padding: "18px",
    color: "#64748b",
    fontSize: "13px",
    textAlign: "center",
    background: "#f8fafc",
  },
  errorBox: {
    border: "1px solid #fecaca",
    borderRadius: "10px",
    background: "#fff1f2",
    color: "#b91c1c",
    padding: "12px",
    marginBottom: "14px",
    fontSize: "13px",
    fontWeight: 700,
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "24px",
    padding: "0 9px",
    borderRadius: "999px",
    fontSize: "11px",
    fontWeight: 800,
    whiteSpace: "nowrap",
  },
  stageLEAD: {
    background: "#f8fafc",
    color: "#475569",
    border: "1px solid #cbd5e1",
  },
  stageMEETING: {
    background: "#ecfeff",
    color: "#0e7490",
    border: "1px solid #a5f3fc",
  },
  stageQUOTE: {
    background: "#eff6ff",
    color: "#1d4ed8",
    border: "1px solid #bfdbfe",
  },
  stageNEGOTIATION: {
    background: "#fffbeb",
    color: "#b45309",
    border: "1px solid #fde68a",
  },
  stageWON: {
    background: "#ecfdf5",
    color: "#047857",
    border: "1px solid #a7f3d0",
  },
  stageLOST: {
    background: "#f1f5f9",
    color: "#64748b",
    border: "1px solid #cbd5e1",
  },
};

