import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "#f5f6f8",
    color: "#111827",
  },
  container: {
    maxWidth: "1120px",
    margin: "0 auto",
    padding: "24px clamp(14px, 4vw, 22px) 48px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "16px",
    flexWrap: "wrap",
    marginBottom: "18px",
  },
  logo: {
    fontSize: "30px",
    fontWeight: 800,
    color: "#0f172a",
    lineHeight: 1,
  },
  title: {
    margin: "8px 0 0",
    fontSize: "22px",
    lineHeight: 1.2,
  },
  subTitle: {
    margin: "8px 0 0",
    color: "#64748b",
    fontSize: "13px",
    lineHeight: 1.55,
  },
  backButton: {
    height: "36px",
    padding: "0 14px",
    borderRadius: "10px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#111827",
    fontSize: "13px",
    fontWeight: 700,
    cursor: "pointer",
  },
  headerRight: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: "8px",
  },
  accountInfo: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  segment: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "8px",
    marginBottom: "14px",
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "8px",
  },
  segmentButton: {
    height: "40px",
    borderRadius: "10px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#475569",
    fontSize: "14px",
    fontWeight: 800,
    cursor: "pointer",
  },
  activeSegmentButton: {
    height: "40px",
    borderRadius: "10px",
    border: "1px solid #111827",
    background: "#111827",
    color: "#ffffff",
    fontSize: "14px",
    fontWeight: 800,
    cursor: "pointer",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: "10px",
    marginBottom: "14px",
  },
  summaryCard: {
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "14px",
  },
  summaryLabel: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
  },
  summaryValue: {
    marginTop: "8px",
    fontSize: "22px",
    fontWeight: 800,
  },
  layout: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(280px, 100%), 1fr))",
    gap: "14px",
    alignItems: "start",
  },
  panel: {
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "18px",
  },
  panelTitle: {
    margin: 0,
    fontSize: "17px",
  },
  panelTopRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
    marginBottom: "8px",
  },
  panelActions: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  panelHint: {
    margin: "6px 0 14px",
    color: "#64748b",
    fontSize: "12px",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(170px, 100%), 1fr))",
    gap: "10px",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: "7px",
    marginBottom: "12px",
  },
  label: {
    color: "#374151",
    fontSize: "12px",
    fontWeight: 800,
  },
  input: {
    width: "100%",
    height: "42px",
    borderRadius: "10px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#111827",
    padding: "0 12px",
    fontSize: "13px",
    outline: "none",
  },
  textarea: {
    minHeight: "90px",
    padding: "12px",
    resize: "vertical",
    lineHeight: 1.5,
  },
  primaryButton: {
    width: "100%",
    height: "44px",
    borderRadius: "10px",
    border: "none",
    background: "#111827",
    color: "#ffffff",
    fontSize: "14px",
    fontWeight: 800,
    cursor: "pointer",
  },
  exportButton: {
    height: "30px",
    padding: "0 10px",
    borderRadius: "8px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#111827",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  customerGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  customerHeader: {
    width: "100%",
    textAlign: "left",
    border: "1px solid #e5e7eb",
    background: "#ffffff",
    borderRadius: "12px",
    padding: "13px",
    cursor: "pointer",
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    alignItems: "center",
  },
  selectedCustomerHeader: {
    width: "100%",
    textAlign: "left",
    border: "1px solid #111827",
    background: "#f8fafc",
    borderRadius: "12px",
    padding: "13px",
    cursor: "pointer",
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    alignItems: "center",
  },
  customerHeaderName: {
    fontSize: "14px",
    fontWeight: 900,
  },
  customerHeaderMeta: {
    marginTop: "4px",
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
  },
  customerHeaderRight: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: "4px",
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 800,
    whiteSpace: "nowrap",
  },
  customerHeaderStage: {
    color: "#0f8a56",
  },
  opportunityBranchList: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    paddingLeft: "18px",
    borderLeft: "2px solid #d9e0ea",
    marginLeft: "12px",
  },
  branchGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  opportunityBranch: {
    position: "relative",
    width: "100%",
    textAlign: "left",
    border: "1px solid #e5e7eb",
    background: "#ffffff",
    borderRadius: "10px",
    padding: "10px 10px 10px 14px",
    cursor: "pointer",
    display: "grid",
    gridTemplateColumns: "auto 1fr auto",
    gap: "8px",
    alignItems: "center",
  },
  selectedOpportunityBranch: {
    position: "relative",
    width: "100%",
    textAlign: "left",
    border: "1px solid #0f8a56",
    background: "#f0fdf4",
    borderRadius: "10px",
    padding: "10px 10px 10px 14px",
    cursor: "pointer",
    display: "grid",
    gridTemplateColumns: "auto 1fr auto",
    gap: "8px",
    alignItems: "center",
  },
  branchLine: {
    width: "8px",
    height: "2px",
    background: "#94a3b8",
  },
  branchContent: {
    minWidth: 0,
  },
  branchTitle: {
    fontSize: "13px",
    fontWeight: 900,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  branchMeta: {
    marginTop: "4px",
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  branchAmount: {
    color: "#0f8a56",
    fontSize: "12px",
    fontWeight: 900,
    whiteSpace: "nowrap",
  },
  childBranchList: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    marginLeft: "24px",
  },
  childBranch: {
    width: "100%",
    textAlign: "left",
    border: "1px dashed #cbd5e1",
    background: "#ffffff",
    borderRadius: "10px",
    padding: "9px 10px",
    cursor: "pointer",
    display: "grid",
    gridTemplateColumns: "auto 1fr auto",
    gap: "8px",
    alignItems: "center",
  },
  selectedChildBranch: {
    width: "100%",
    textAlign: "left",
    border: "1px solid #0f8a56",
    background: "#ecfdf5",
    borderRadius: "10px",
    padding: "9px 10px",
    cursor: "pointer",
    display: "grid",
    gridTemplateColumns: "auto 1fr auto",
    gap: "8px",
    alignItems: "center",
  },
  childBranchMark: {
    color: "#64748b",
    fontSize: "13px",
    fontWeight: 900,
  },
  card: {
    width: "100%",
    textAlign: "left",
    border: "1px solid #e5e7eb",
    background: "#ffffff",
    borderRadius: "12px",
    padding: "13px",
    cursor: "pointer",
  },
  selectedCard: {
    width: "100%",
    textAlign: "left",
    border: "1px solid #111827",
    background: "#f8fafc",
    borderRadius: "12px",
    padding: "13px",
    cursor: "pointer",
  },
  simpleCardRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    alignItems: "center",
    minHeight: "24px",
  },
  company: {
    fontSize: "14px",
    fontWeight: 800,
  },
  contact: {
    color: "#64748b",
    fontSize: "13px",
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  cardTop: {
    display: "flex",
    justifyContent: "space-between",
    gap: "10px",
    alignItems: "center",
  },
  item: {
    marginTop: "7px",
    fontSize: "13px",
    color: "#334155",
  },
  meta: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    marginTop: "9px",
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
  },
  nextAction: {
    marginTop: "10px",
    borderRadius: "10px",
    background: "#f8fafc",
    border: "1px solid #e5e7eb",
    padding: "10px",
    color: "#334155",
    fontSize: "12px",
  },
  detailPanel: {
    marginTop: "14px",
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "18px",
  },
  detailHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  detailMeta: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
  },
  detailTitle: {
    margin: "6px 0 0",
    fontSize: "18px",
  },
  linkedParentInfo: {
    display: "inline-flex",
    marginTop: "8px",
    borderRadius: "999px",
    background: "#eef2f7",
    color: "#475569",
    padding: "5px 9px",
    fontSize: "12px",
    fontWeight: 800,
  },
  deleteButton: {
    height: "34px",
    padding: "0 12px",
    borderRadius: "9px",
    border: "1px solid #fecaca",
    background: "#fef2f2",
    color: "#dc2626",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
  },
  detailGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(170px, 100%), 1fr))",
    gap: "10px",
    marginTop: "14px",
  },
  detailBox: {
    border: "1px solid #e5e7eb",
    borderRadius: "10px",
    padding: "12px",
    background: "#f8fafc",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    fontSize: "13px",
  },
  detailLabel: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
  },
  empty: {
    border: "1px dashed #cbd5e1",
    borderRadius: "10px",
    padding: "18px",
    color: "#64748b",
    fontSize: "13px",
    textAlign: "center",
    background: "#f8fafc",
  },
  errorBox: {
    border: "1px solid #fecaca",
    borderRadius: "10px",
    background: "#fff1f2",
    color: "#b91c1c",
    padding: "12px",
    marginBottom: "14px",
    fontSize: "13px",
    fontWeight: 700,
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "24px",
    padding: "0 9px",
    borderRadius: "999px",
    fontSize: "11px",
    fontWeight: 800,
    whiteSpace: "nowrap",
  },
  stageLEAD: {
    background: "#f8fafc",
    color: "#475569",
    border: "1px solid #cbd5e1",
  },
  stageMEETING: {
    background: "#ecfeff",
    color: "#0e7490",
    border: "1px solid #a5f3fc",
  },
  stageQUOTE: {
    background: "#eff6ff",
    color: "#1d4ed8",
    border: "1px solid #bfdbfe",
  },
  stageNEGOTIATION: {
    background: "#fffbeb",
    color: "#b45309",
    border: "1px solid #fde68a",
  },
  stageWON: {
    background: "#ecfdf5",
    color: "#047857",
    border: "1px solid #a7f3d0",
  },
  stageLOST: {
    background: "#f1f5f9",
    color: "#64748b",
    border: "1px solid #cbd5e1",
  },
};

