import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "#f5f6f8",
    color: "#111827",
  },
  pageMobile: {
    background: "#f3f5f7",
  },
  container: {
    maxWidth: "1120px",
    margin: "0 auto",
    padding: "24px clamp(14px, 4vw, 22px) 48px",
  },
  containerMobile: {
    padding: "0 0 20px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "16px",
    flexWrap: "wrap",
    marginBottom: "18px",
  },
  logo: {
    fontSize: "30px",
    fontWeight: 800,
    color: "#0f172a",
    lineHeight: 1,
  },
  title: {
    margin: "8px 0 0",
    fontSize: "22px",
    lineHeight: 1.2,
  },
  subTitle: {
    margin: "8px 0 0",
    color: "#64748b",
    fontSize: "13px",
    lineHeight: 1.55,
  },
  headerRight: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: "8px",
  },
  accountInfo: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  backButton: {
    height: "36px",
    padding: "0 14px",
    borderRadius: "10px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#111827",
    fontSize: "13px",
    fontWeight: 700,
    cursor: "pointer",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: "10px",
    marginBottom: "14px",
  },
  summaryGridMobile: {
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "7px",
    marginBottom: "10px",
  },
  summaryCard: {
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "14px",
  },
  summaryLabel: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
  },
  summaryValue: {
    marginTop: "8px",
    fontSize: "22px",
    fontWeight: 800,
  },
  layout: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(280px, 100%), 1fr))",
    gap: "14px",
    alignItems: "start",
  },
  layoutMobile: {
    gridTemplateColumns: "minmax(0, 1fr)",
    gap: "10px",
  },
  leftColumn: {
    display: "flex",
    flexDirection: "column",
    gap: "14px",
  },
  panel: {
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "18px",
  },
  panelMobile: {
    borderRadius: "10px",
    padding: "13px",
  },
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
    marginBottom: "14px",
  },
  panelHeaderMobile: {
    alignItems: "stretch",
  },
  panelTitle: {
    margin: 0,
    fontSize: "17px",
  },
  panelHint: {
    margin: "6px 0 14px",
    color: "#64748b",
    fontSize: "12px",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(170px, 100%), 1fr))",
    gap: "10px",
  },
  formGridMobile: {
    gridTemplateColumns: "minmax(0, 1fr)",
    gap: "8px",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: "7px",
    marginBottom: "12px",
  },
  label: {
    color: "#374151",
    fontSize: "12px",
    fontWeight: 800,
  },
  input: {
    width: "100%",
    height: "42px",
    borderRadius: "10px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#111827",
    padding: "0 12px",
    fontSize: "13px",
    outline: "none",
  },
  textarea: {
    minHeight: "80px",
    padding: "12px",
    resize: "vertical",
    lineHeight: 1.5,
  },
  primaryButton: {
    width: "100%",
    height: "44px",
    borderRadius: "10px",
    border: "none",
    background: "#111827",
    color: "#ffffff",
    fontSize: "14px",
    fontWeight: 800,
    cursor: "pointer",
  },
  smallPrimaryButton: {
    height: "34px",
    padding: "0 12px",
    borderRadius: "9px",
    border: "none",
    background: "#111827",
    color: "#ffffff",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  customerList: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  categorySection: {
    border: "1px solid #e5e7eb",
    borderRadius: "10px",
    background: "#ffffff",
    overflow: "hidden",
  },
  categoryHeader: {
    width: "100%",
    minHeight: "42px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto auto",
    alignItems: "center",
    gap: "8px",
    border: "none",
    background: "#f8fafc",
    color: "#111827",
    padding: "0 12px",
    cursor: "pointer",
    textAlign: "left",
    fontSize: "13px",
    fontWeight: 850,
  },
  categoryArrow: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "22px",
    height: "22px",
    borderRadius: "999px",
    color: "#667085",
    transition: "transform 120ms ease",
  },
  categoryBody: {
    display: "grid",
    gap: "8px",
    padding: "8px",
  },
  categoryEmpty: {
    border: "1px dashed #d6dce5",
    borderRadius: "8px",
    color: "#667085",
    padding: "12px",
    textAlign: "center",
    fontSize: "12px",
    fontWeight: 700,
  },
  customerCard: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
    border: "1px solid #e5e7eb",
    background: "#ffffff",
    borderRadius: "10px",
    padding: "12px",
    cursor: "pointer",
  },
  selectedCustomerCard: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
    border: "1px solid #111827",
    background: "#f8fafc",
    borderRadius: "10px",
    padding: "12px",
    cursor: "pointer",
  },
  customerName: {
    fontSize: "14px",
    fontWeight: 800,
  },
  customerMeta: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  detailHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "12px",
    flexWrap: "wrap",
  },
  detailHeaderMobile: {
    flexDirection: "column",
  },
  detailActions: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  detailActionsMobile: {
    width: "100%",
    justifyContent: "flex-start",
  },
  detailMeta: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
  },
  detailTitle: {
    margin: "6px 0 0",
    fontSize: "19px",
  },
  categoryPill: {
    display: "inline-flex",
    alignItems: "center",
    height: "24px",
    marginTop: "8px",
    padding: "0 9px",
    borderRadius: "999px",
    background: "#eef6f1",
    color: "#047857",
    fontSize: "12px",
    fontWeight: 850,
  },
  deleteButton: {
    height: "34px",
    padding: "0 12px",
    borderRadius: "9px",
    border: "1px solid #fecaca",
    background: "#fef2f2",
    color: "#dc2626",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
  },
  editButton: {
    height: "34px",
    padding: "0 12px",
    borderRadius: "9px",
    border: "1px solid #bfdbfe",
    background: "#eff6ff",
    color: "#1d4ed8",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
  },
  infoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(150px, 100%), 1fr))",
    gap: "10px",
    marginTop: "14px",
  },
  infoBox: {
    border: "1px solid #e5e7eb",
    borderRadius: "10px",
    background: "#f8fafc",
    padding: "12px",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  infoLabel: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
  },
  infoValue: {
    fontSize: "13px",
  },
  memoBox: {
    marginTop: "12px",
    border: "1px solid #e5e7eb",
    borderRadius: "10px",
    background: "#ffffff",
    padding: "12px",
    color: "#374151",
    fontSize: "13px",
    lineHeight: 1.55,
  },
  sectionTitle: {
    margin: 0,
    fontSize: "15px",
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    marginBottom: "12px",
  },
  contactList: {
    marginTop: "18px",
  },
  equipmentSection: {
    marginTop: "18px",
    borderTop: "1px solid #e5e7eb",
    paddingTop: "16px",
  },
  equipmentList: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(210px, 100%), 1fr))",
    gap: "8px",
  },
  equipmentCard: {
    minHeight: "54px",
    border: "1px solid #e5e7eb",
    borderRadius: "10px",
    background: "#ffffff",
    padding: "10px 12px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "5px 10px",
    textAlign: "left",
    alignItems: "center",
    cursor: "pointer",
  },
  equipmentCardTitle: {
    minWidth: 0,
    color: "#111827",
    fontSize: "13px",
    fontWeight: 850,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  equipmentCardMeta: {
    minWidth: 0,
    gridColumn: "1 / -1",
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  equipmentCardBadge: {
    gridColumn: 2,
    gridRow: 1,
    border: "1px solid #bbf7d0",
    borderRadius: "999px",
    background: "#f0fdf4",
    color: "#047857",
    padding: "3px 8px",
    fontSize: "11px",
    fontWeight: 850,
    whiteSpace: "nowrap",
  },
  contactRow: {
    width: "100%",
    minHeight: "42px",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    background: "#ffffff",
    padding: "0 12px",
    marginBottom: "8px",
    display: "grid",
    gridTemplateColumns: "minmax(90px, 1fr) minmax(70px, 0.7fr) minmax(110px, 1fr)",
    alignItems: "center",
    gap: "10px",
    textAlign: "left",
    color: "#0f172a",
    cursor: "pointer",
  },
  contactRowMobile: {
    gridTemplateColumns: "minmax(0, 1fr)",
    alignItems: "start",
    gap: "4px",
    padding: "10px 12px",
  },
  contactRowName: {
    minWidth: 0,
    fontSize: "13px",
    fontWeight: 800,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  contactRowMeta: {
    minWidth: 0,
    color: "#475569",
    fontSize: "12px",
    fontWeight: 700,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  contactRowPhone: {
    minWidth: 0,
    color: "#334155",
    fontSize: "12px",
    fontWeight: 700,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    textAlign: "right",
  },
  contactRowPhoneMobile: {
    textAlign: "left",
  },
  contactCard: {
    border: "1px solid #e5e7eb",
    borderRadius: "10px",
    padding: "12px",
    marginBottom: "10px",
  },
  contactTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "10px",
  },
  contactName: {
    fontSize: "14px",
    fontWeight: 800,
  },
  contactMeta: {
    marginTop: "5px",
    color: "#64748b",
    fontSize: "12px",
  },
  smallDeleteButton: {
    height: "30px",
    padding: "0 10px",
    borderRadius: "8px",
    border: "1px solid #e5e7eb",
    background: "#ffffff",
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
    cursor: "pointer",
  },
  contactDetail: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    marginTop: "9px",
    color: "#334155",
    fontSize: "12px",
    fontWeight: 700,
  },
  contactMemo: {
    marginTop: "8px",
    color: "#64748b",
    fontSize: "12px",
    lineHeight: 1.5,
  },
  empty: {
    border: "1px dashed #cbd5e1",
    borderRadius: "10px",
    padding: "18px",
    color: "#64748b",
    fontSize: "13px",
    textAlign: "center",
    background: "#f8fafc",
  },
  errorBox: {
    border: "1px solid #fecaca",
    borderRadius: "10px",
    background: "#fff1f2",
    color: "#b91c1c",
    padding: "12px",
    marginBottom: "14px",
    fontSize: "13px",
    fontWeight: 700,
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 50,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(15, 23, 42, 0.36)",
    padding: "20px",
  },
  modal: {
    width: "100%",
    maxWidth: "520px",
    maxHeight: "calc(100vh - 40px)",
    overflow: "auto",
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "18px",
    boxShadow: "0 20px 60px rgba(15, 23, 42, 0.24)",
  },
  modalMobile: {
    maxWidth: "none",
    maxHeight: "calc(100dvh - 24px)",
    borderRadius: "12px",
    padding: "14px",
  },
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    marginBottom: "14px",
  },
  modalHeaderActions: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    flex: "0 0 auto",
  },
  detailGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(150px, 100%), 1fr))",
    gap: "10px",
  },
  modalMemo: {
    marginTop: "12px",
    border: "1px solid #e5e7eb",
    borderRadius: "10px",
    background: "#f8fafc",
    padding: "12px",
    color: "#334155",
    fontSize: "13px",
    lineHeight: 1.55,
  },
  equipmentHistory: {
    marginTop: "16px",
  },
  equipmentHistoryScroll: {
    maxHeight: "320px",
    overflowY: "auto",
    paddingRight: "4px",
  },
  historyBlock: {
    border: "1px solid #e5e7eb",
    borderRadius: "10px",
    padding: "12px",
    marginTop: "10px",
  },
  historyTitle: {
    color: "#111827",
    fontSize: "13px",
    fontWeight: 850,
  },
  historyList: {
    marginTop: "9px",
    display: "grid",
    gap: "7px",
  },
  historyItem: {
    display: "grid",
    gridTemplateColumns: "82px minmax(0, 1fr)",
    gap: "8px",
    borderTop: "1px solid #eef2f7",
    paddingTop: "7px",
    color: "#334155",
    fontSize: "12px",
  },
  historyEmpty: {
    marginTop: "8px",
    color: "#94a3b8",
    fontSize: "12px",
    fontWeight: 700,
  },
  modalDeleteButton: {
    height: "32px",
    padding: "0 10px",
    borderRadius: "8px",
    border: "1px solid #fecaca",
    background: "#fff1f2",
    color: "#dc2626",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
  },
  closeButton: {
    height: "32px",
    padding: "0 11px",
    borderRadius: "8px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#111827",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
  },
};



