import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "#f5f6f8",
    color: "#111827",
  },
  container: {
    maxWidth: "1120px",
    margin: "0 auto",
    padding: "24px clamp(14px, 4vw, 22px) 48px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "16px",
    flexWrap: "wrap",
    marginBottom: "18px",
  },
  logo: {
    fontSize: "30px",
    fontWeight: 800,
    color: "#0f172a",
    lineHeight: 1,
  },
  title: {
    margin: "8px 0 0",
    fontSize: "22px",
    lineHeight: 1.2,
  },
  subTitle: {
    margin: "8px 0 0",
    color: "#64748b",
    fontSize: "13px",
    lineHeight: 1.55,
  },
  headerRight: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: "8px",
  },
  accountInfo: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  backButton: {
    height: "36px",
    padding: "0 14px",
    borderRadius: "10px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#111827",
    fontSize: "13px",
    fontWeight: 700,
    cursor: "pointer",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: "10px",
    marginBottom: "14px",
  },
  summaryCard: {
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "14px",
  },
  summaryLabel: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
  },
  summaryValue: {
    marginTop: "8px",
    fontSize: "22px",
    fontWeight: 800,
  },
  layout: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(280px, 100%), 1fr))",
    gap: "14px",
    alignItems: "start",
  },
  leftColumn: {
    display: "flex",
    flexDirection: "column",
    gap: "14px",
  },
  panel: {
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "18px",
  },
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
    marginBottom: "14px",
  },
  panelTitle: {
    margin: 0,
    fontSize: "17px",
  },
  panelHint: {
    margin: "6px 0 14px",
    color: "#64748b",
    fontSize: "12px",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(170px, 100%), 1fr))",
    gap: "10px",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: "7px",
    marginBottom: "12px",
  },
  label: {
    color: "#374151",
    fontSize: "12px",
    fontWeight: 800,
  },
  input: {
    width: "100%",
    height: "42px",
    borderRadius: "10px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#111827",
    padding: "0 12px",
    fontSize: "13px",
    outline: "none",
  },
  textarea: {
    minHeight: "80px",
    padding: "12px",
    resize: "vertical",
    lineHeight: 1.5,
  },
  primaryButton: {
    width: "100%",
    height: "44px",
    borderRadius: "10px",
    border: "none",
    background: "#111827",
    color: "#ffffff",
    fontSize: "14px",
    fontWeight: 800,
    cursor: "pointer",
  },
  smallPrimaryButton: {
    height: "34px",
    padding: "0 12px",
    borderRadius: "9px",
    border: "none",
    background: "#111827",
    color: "#ffffff",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  customerList: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  customerCard: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
    border: "1px solid #e5e7eb",
    background: "#ffffff",
    borderRadius: "10px",
    padding: "12px",
    cursor: "pointer",
  },
  selectedCustomerCard: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
    border: "1px solid #111827",
    background: "#f8fafc",
    borderRadius: "10px",
    padding: "12px",
    cursor: "pointer",
  },
  customerName: {
    fontSize: "14px",
    fontWeight: 800,
  },
  customerMeta: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  detailHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "12px",
    flexWrap: "wrap",
  },
  detailMeta: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
  },
  detailTitle: {
    margin: "6px 0 0",
    fontSize: "19px",
  },
  deleteButton: {
    height: "34px",
    padding: "0 12px",
    borderRadius: "9px",
    border: "1px solid #fecaca",
    background: "#fef2f2",
    color: "#dc2626",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
  },
  infoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(150px, 100%), 1fr))",
    gap: "10px",
    marginTop: "14px",
  },
  infoBox: {
    border: "1px solid #e5e7eb",
    borderRadius: "10px",
    background: "#f8fafc",
    padding: "12px",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  infoLabel: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
  },
  infoValue: {
    fontSize: "13px",
  },
  memoBox: {
    marginTop: "12px",
    border: "1px solid #e5e7eb",
    borderRadius: "10px",
    background: "#ffffff",
    padding: "12px",
    color: "#374151",
    fontSize: "13px",
    lineHeight: 1.55,
  },
  sectionTitle: {
    margin: 0,
    fontSize: "15px",
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    marginBottom: "12px",
  },
  contactList: {
    marginTop: "18px",
  },
  contactRow: {
    width: "100%",
    minHeight: "42px",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    background: "#ffffff",
    padding: "0 12px",
    marginBottom: "8px",
    display: "grid",
    gridTemplateColumns: "minmax(90px, 1fr) minmax(70px, 0.7fr) minmax(110px, 1fr)",
    alignItems: "center",
    gap: "10px",
    textAlign: "left",
    color: "#0f172a",
    cursor: "pointer",
  },
  contactRowName: {
    minWidth: 0,
    fontSize: "13px",
    fontWeight: 800,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  contactRowMeta: {
    minWidth: 0,
    color: "#475569",
    fontSize: "12px",
    fontWeight: 700,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  contactRowPhone: {
    minWidth: 0,
    color: "#334155",
    fontSize: "12px",
    fontWeight: 700,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    textAlign: "right",
  },
  contactCard: {
    border: "1px solid #e5e7eb",
    borderRadius: "10px",
    padding: "12px",
    marginBottom: "10px",
  },
  contactTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "10px",
  },
  contactName: {
    fontSize: "14px",
    fontWeight: 800,
  },
  contactMeta: {
    marginTop: "5px",
    color: "#64748b",
    fontSize: "12px",
  },
  smallDeleteButton: {
    height: "30px",
    padding: "0 10px",
    borderRadius: "8px",
    border: "1px solid #e5e7eb",
    background: "#ffffff",
    color: "#64748b",
    fontSize: "12px",
    fontWeight: 700,
    cursor: "pointer",
  },
  contactDetail: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    marginTop: "9px",
    color: "#334155",
    fontSize: "12px",
    fontWeight: 700,
  },
  contactMemo: {
    marginTop: "8px",
    color: "#64748b",
    fontSize: "12px",
    lineHeight: 1.5,
  },
  empty: {
    border: "1px dashed #cbd5e1",
    borderRadius: "10px",
    padding: "18px",
    color: "#64748b",
    fontSize: "13px",
    textAlign: "center",
    background: "#f8fafc",
  },
  errorBox: {
    border: "1px solid #fecaca",
    borderRadius: "10px",
    background: "#fff1f2",
    color: "#b91c1c",
    padding: "12px",
    marginBottom: "14px",
    fontSize: "13px",
    fontWeight: 700,
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 50,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(15, 23, 42, 0.36)",
    padding: "20px",
  },
  modal: {
    width: "100%",
    maxWidth: "520px",
    maxHeight: "calc(100vh - 40px)",
    overflow: "auto",
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "12px",
    padding: "18px",
    boxShadow: "0 20px 60px rgba(15, 23, 42, 0.24)",
  },
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    marginBottom: "14px",
  },
  detailGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(150px, 100%), 1fr))",
    gap: "10px",
  },
  modalMemo: {
    marginTop: "12px",
    border: "1px solid #e5e7eb",
    borderRadius: "10px",
    background: "#f8fafc",
    padding: "12px",
    color: "#334155",
    fontSize: "13px",
    lineHeight: 1.55,
  },
  modalDeleteButton: {
    width: "100%",
    height: "42px",
    marginTop: "14px",
    borderRadius: "8px",
    border: "1px solid #fecaca",
    background: "#fff1f2",
    color: "#dc2626",
    fontSize: "13px",
    fontWeight: 800,
    cursor: "pointer",
  },
  closeButton: {
    height: "32px",
    padding: "0 11px",
    borderRadius: "8px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#111827",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
  },
};



